version: '3.4'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
     - "16686:16686"

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"

  api:
    image: ${DOCKER_REGISTRY-}abbntierwebapi
    build:
      context: .
      dockerfile: src/ABB.3Tier.WebApi/Dockerfile
    environment:
      CONNECTIONSTRINGS_MOTORSCONTEXT: "db"
      JAEGER__JAEGER_AGENT_HOST: "jaeger"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - .nginx/logs/:/var/log/nginx/
      - ./src/ABB.3Tier.WebUI/dist:/usr/share/nginx/html:ro
    ports:
      - '8080:80'
    depends_on:
      - api
    restart: always